import pandas as pd

def preencher_mrosc(    df_mrosc,
                         pvtn,
                         comunitario,
                         familiar,
                         ref_creas,
                         transferidos,
                         desligados,
                         total_acolhidos,
                         obitos,
                         total_acolhidos_final,
                         recepcionados,
                         bf,
                         bpc,
                         n_benef,
                         outro_benef,
                         inscr_cad,
                         formal,
                         informal,
                         estrangeiros,
                         cont_refugiados,
                         imigrantes,
                         cont_processo,
                         cont_lib_condicional,
                         cont_egressos
                         ):
    dados = {
    'pvtn': pvtn,
    'comunitario': comunitario,
    'familiar': familiar,
    'ref_creas': ref_creas,
    'transferidos': transferidos,
    'desligados': desligados,
    'total_acolhidos': total_acolhidos,
    'obitos': obitos,
    'total_acolhidos_final': total_acolhidos_final,
    'recepcionados': recepcionados,
    'bf': bf,
    'bpc': bpc,
    'n_benef': n_benef,
    'outro_benef': outro_benef,
    'inscr_cad': inscr_cad,
    'formal': formal,
    'informal': informal,
    'estrangeiros': estrangeiros,
    'cont_refugiados': cont_refugiados,
    'imigrantes': imigrantes,
    'cont_processo': cont_processo,
    'cont_lib_condicional': cont_lib_condicional,
    'cont_egressos': cont_egressos
    }

    df_mrosc['RESULTADOS'] = [dados['recepcionados'], dados['transferidos'], dados['desligados'], dados['familiar'],
                              dados['comunitario'], 0, dados['pvtn'], dados['ref_creas'], dados['total_acolhidos_final'],
                              0, '', 0, 0, 0, '', 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, '', dados['inscr_cad'], dados['n_benef'],
                              0, '', 0, dados['formal'], dados['informal'], 0, dados['bpc'], dados['bf'], dados['n_benef'],'',
                              0, 0]

    return df_mrosc